### PR TITLE
Converted Extension persistent background page to event page.

### PR DESCRIPTION
**Pull request by beaufortfrancois**
From http://developer.chrome.com/extensions/event_pages.html,
_Event pages are very similar to background pages, with one important difference: event pages are loaded only when they are needed. When the event page is not actively doing something, it is unloaded, freeing memory and other system resources._

It's pretty easy to do so. Let me know if it works for you.

snp9upt

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
I've also noticed some manifest permissions were not used (as far as I know) and took the liberty of removing them.

I think people would be more inclined to install an extension that says "No special permission" than "Access to jstorrent.com and *.jstorrent.com" when it's just about adding a Context Menu.

**Comment by kzahel** [comment]
Sweet, I think there was some reason why I was using a persistent background page, but I can't remember. I'll have to do some testing to make sure it doesn't break anything.

Regarding the extension permissions - I am planning on adding some functionality to the website where it will need to communicate with the app. However, this may be unnecessary now that onMessageExternal is going stable or is already stable(?) I'll have to think about this some more...

**Comment by beaufortfrancois** [comment]
I didn't remove the `notifications` permission since as you says, you do use them. With a persistent background page, I've got 22Mo of memory that are used for pretty much nothing.
If some stuff don't work anymore, please let me know and I'll fix them.

Regarding `onMessageExternal`, if it's not stable now it will be soon for sure.

**Comment by kzahel** [comment]
Yeah you're right, and the new extension policy is to have single-purpose extensions, so this is more in line with that :-) Yeah it looks like onMessageExternal can have the app receive messages from the webpage, so that permission was unnecessary.

**Comment by beaufortfrancois** [comment]
Not sure if you have that in mind, but you could register the jstorrent.com as a `magnet:` protocol handler so that each time I click on a magnet link, I'm being redirected to the jstorrent.com website which summons the jstorrent app (if it's installed) with the magnet info.

See http://updates.html5rocks.com/2011/06/Registering-a-custom-protocol-handler if it's not clear.

**Comment by kzahel** [comment]
Yeah there's no way to register custom protocols except a few whitelisted
ones AFAIK, unless this has changed recently.
You can only register protocol handlers that are prefixed with "web" i.e.
"web+magnet:"
It would be awesome if there were a way to do this for ChromeOS, at least.

On Sun, Feb 9, 2014 at 11:55 AM, François Beaufort <notifications@github.com

**Comment by beaufortfrancois** [comment]
You can actually do that in Chrome:

```
navigator.registerProtocolHandler('magnet', document.URL + '?q=%s', 'My Torrent App');
```

It works fine! Give it a try ;)

**Comment by kzahel** [comment]
AWESOME!
https://github.com/JSTorrent/jstorrent.github.io/commit/a1646d3cc9455766833f8a13c8c6bb2819c81769
see if it works for you (just visit jstorrent.com and you should see the thing in the URL bar)

I used to be so mad that registerProtocolHandler only worked for mailto and a couple others, glad its whitelisted (probably ChromeOS only, right?)

**Comment by kzahel** [comment]
Now I have a reason to improve that /share page and have it try to do inline install and do onMessageExternal stuff :-) Thanks!

**Comment by kzahel** [comment]
Hmm, it's pretty annoying that it doesn't open up the protocol handler webpage in a new window. That annoys me about mailto: links too, that they never open in a new window, so I lose the webpage I was on :-( registerProtocolHandler should have an option to have it open in a new window by default imo

**Comment by beaufortfrancois** [comment]
According to https://chromiumcodereview.appspot.com/18234004, it looks like the `magnet` protocol has been added 7 months ago. I didn't notice either to be honest ;)

I've tried your page and it works fine. All you need is to communicate with your Chrome App now to launch it I guess!

And I agree with you, the bubble should prompt. Nobody's gonna click on it if you don't tell it for sure ;(

**Pull request merged**
